#!/bin/bash

sed \
-e "s/\${ENV}/$ENV/" \
-e "s/\${GOOGLE_LOGIN}/$GOOGLE_LOGIN/" \
-e "s/\${GOOGLE_PASSWORD}/$GOOGLE_PASSWRD/" \
-e "s/\${GOOGLE_CONSUMER_KEY}/$GOOGLE_CONSUMER_KEY/" \
-e "s/\${GOOGLE_CONSUMER_SECRET}/$GOOGLE_CONSUMER_SECRET/" \
-e "s/\${EMAIL_USERNAME}/$EMAIL_USERNAME/" \
-e "s/\${EMAIL_PASSWORD}/$EMAIL_PASSWORD/" \
$1 > $2
